//  Copyright (c) 2012, Rob J Meijer
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.
#include <iostream>
#include <string>
#include <TripleHashLookup.hpp>

void printkey(capfs::TripleHashNode const &node,std::string name) {
  std::cerr << name << ":" << std::endl;
  std::cout << "\trw=" << node.rwcap() << std::endl;
  std::cout << "\tro=" << node.rocap() << std::endl;
  std::cout << "\tsp=" << node.rawpath() << std::endl;
} 

void printparentchild(capfs::TripleHashParentChild const pc,std::string name) {
  printkey(pc.parent(),name + "::parent");
  printkey(pc.child(),name + "::child");
}

int main(int argc,char **argv){
  capfs::TripleHashLookup triplehash("ThisIsASPrettyBadSecretSalt");
  printparentchild(triplehash["/rw-ABCDEFGHIJKLMNOPQRSTUVWXYZ234567ABCDEFGHIJKLMNOPQRST/Foo/Bar/Bla.txt"],"l4"); 
  printparentchild(triplehash["/rw-ABCDEFGHIJKLMNOPQRSTUVWXYZ234567ABCDEFGHIJKLMNOPQRST/Foo"],"l2");
  printparentchild(triplehash["/rw-ABCDEFGHIJKLMNOPQRSTUVWXYZ234567ABCDEFGHIJKLMNOPQRST"],"l1");
  printparentchild(triplehash["/"],"l0");
  printparentchild(triplehash["/bogus"],"bogus"); 
}
